name: rnamsm
channels:
  - pytorch
  - bioconda
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - autopep8=1.5.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - biopython=1.78=py38h7f8727e_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - boto3=1.21.27=pyhd8ed1ab_0
  - botocore=1.24.27=pyhd8ed1ab_0
  - bottleneck=1.3.4=py38hce1f21e_0
  - brotlipy=0.7.0=py38h8df0ef7_1001
  - ca-certificates=2022.5.18.1=ha878542_0
  - certifi=2022.5.18.1=py38h578d9bd_0
  - cffi=1.14.5=py38h261ae71_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - cryptography=35.0.0=py38ha5dfef3_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - cycler=0.10.0=py38_0
  - cython=0.29.21=py38h2531618_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.6.0=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - expat=2.2.10=he6710b0_2
  - filelock=3.6.0=pyhd8ed1ab_0
  - flake8=3.8.4=py_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.67.4=h36276a3_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hhsuite=3.3.0=py38pl526h6ed170a_1
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd8ed1ab_0
  - importlib_metadata=2.0.0=1
  - infernal=1.1.2=h516909a_3
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.20.0=py38hb070fc8_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - jedi=0.17.0=py38_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jmespath=1.0.0=pyhd8ed1ab_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.1=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.1=py38h2531618_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.3.0=h5101ec6_17
  - libllvm11=11.1.0=h3826bc1_1
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.19.1=h4ff587b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - llvmlite=0.38.0=py38h4ff587b_0
  - lz4-c=1.9.3=h2531618_0
  - matplotlib=3.3.4=py38h06a4308_0
  - matplotlib-base=3.3.4=py38h62a2d02_0
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.1=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - more-itertools=8.7.0=pyhd3eb1b0_0
  - mypy=0.800=pyhd3eb1b0_0
  - mypy_extensions=0.4.3=py38_0
  - nbclient=0.5.2=pyhd3eb1b0_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - ninja=1.10.2=py38hff7bd54_0
  - nodejs=6.13.1=0
  - notebook=6.2.0=py38h06a4308_0
  - numba=0.55.1=py38h51133e4_0
  - numexpr=2.7.3=py38hb2eb853_0
  - olefile=0.46=py_0
  - openssl=1.1.1q=h7f8727e_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.3=py38h06a4308_1
  - parso=0.8.1=pyhd3eb1b0_0
  - pcre=8.44=he6710b0_0
  - perl=5.26.2=h36c2ea0_1008
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.0=py38he98fc37_0
  - pip=21.0.1=py38h06a4308_0
  - pluggy=0.13.1=py38_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - protobuf=3.19.1=py38h295c915_0
  - psutil=5.8.0=py38h27cfd23_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.10.0=pyhd3eb1b0_0
  - pycodestyle=2.6.0=pyhd3eb1b0_0
  - pycparser=2.20=py_2
  - pyflakes=2.2.0=pyhd3eb1b0_0
  - pygments=2.8.0=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h7b6447c_0
  - pysocks=1.7.1=py38h578d9bd_4
  - pytest=6.2.2=py38h06a4308_2
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python-lmdb=1.2.1=py38h2531618_1
  - python_abi=3.8=2_cp38
  - pytorch=1.7.1=py3.8_cuda11.0.221_cudnn8.0.5_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyzmq=20.0.0=py38h2531618_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.0.2=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - readline=8.1=h27cfd23_0
  - requests=2.27.1=pyhd8ed1ab_0
  - s3transfer=0.5.2=pyhd8ed1ab_0
  - scipy=1.6.0=py38h91f5cce_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tape_proteins=0.5=pyhd8ed1ab_0
  - tbb=2021.5.0=hd09550d_0
  - tensorboardx=2.5=pyhd8ed1ab_0
  - terminado=0.9.2=py38h06a4308_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - torchaudio=0.7.2=py38
  - torchvision=0.8.2=py38_cu110
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typed-ast=1.4.2=py38h27cfd23_1
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py38_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.8
    - async-timeout==4.0.2
    - cachetools==5.2.0
    - click==8.1.3
    - fair-msm==1.0.2
    - frozenlist==1.3.0
    - fsspec==2022.5.0
    - future==0.18.2
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - huggingface-hub==0.8.1
    - hydra==2.5
    - hydra-core==1.1.1
    - importlib-metadata==4.12.0
    - importlib-resources==5.8.0
    - joblib==1.1.0
    - lxml==4.9.1
    - markdown==3.4.1
    - markupsafe==2.0.1
    - multidict==6.0.2
    - numpy==1.19.2
    - oauthlib==3.2.0
    - omegaconf==2.1.2
    - pandas==1.3.1
    - pandas-datareader==0.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pytorch-lightning==1.5.10
    - pyyaml==5.4.1
    - regex==2022.3.15
    - requests-oauthlib==1.3.1
    - rna-fm==0.1.0
    - rsa==4.8
    - sacremoses==0.0.49
    - scikit-learn==0.24.0
    - setuptools==59.5.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - torchmetrics==0.7.3
    - torchsummary==1.5.1
    - tqdm==4.62.0
    - transformers==4.17.0
    - werkzeug==2.0.3
    - yarl==1.7.2
prefix: /home/kk/anaconda3/envs/jjh_proteins
